version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      IMG_PROC_SAVE_PATH: "/images"
    volumes:
      - "./data:/images"
    ports:
      - "9000"
    logging:
      driver: "json-file"
