// Code generated by GoTool. DO NOT EDIT.

package service

import (
	"context"

	"github.com/go-kit/kit/endpoint"
)

type Set struct {
	ResizeEndpoint      endpoint.Endpoint
	ResizeByURLEndpoint endpoint.Endpoint
}

func makeResizeEndpoint(s Interface) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(ResizeRequest)
		err := s.Resize(ctx, req.Data, req.Width, req.Height)
		return ResizeResponse{Err: err}, nil
	}
}

func makeResizeByURLEndpoint(s Interface) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(ResizeByURLRequest)
		err := s.ResizeByURL(ctx, req.URL, req.Width, req.Height)
		return ResizeByURLResponse{Err: err}, nil
	}
}

func MakeEndpoints(s Interface) (set Set) {
	set.ResizeEndpoint = makeResizeEndpoint(s)
	set.ResizeByURLEndpoint = makeResizeByURLEndpoint(s)
	return
}

type ResizeRequest struct {
	Data   []byte `json:"data"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type ResizeResponse struct {
	Err error `json:"err,omitempty"`
}

func (r ResizeResponse) Failed() error {
	return r.Err
}

type ResizeByURLRequest struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type ResizeByURLResponse struct {
	Err error `json:"err,omitempty"`
}

func (r ResizeByURLResponse) Failed() error {
	return r.Err
}
