// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/transport/http"
	"github.com/l-vitaly/imgprocessing/pkg/service"
	http2 "net/http"
)

// Injectors from wire.go:

func SetupHTTPHandler(savedPath string, logger log.Logger, opts ...http.ServerOption) (http2.Handler, func(), error) {
	serviceService := service.NewService(savedPath)
	set := service.MakeEndpoints(serviceService)
	encodeDecodeSet := service.MakeEncodeDecodeSet()
	handler := service.NewHTTPHandler(serviceService, set, encodeDecodeSet, logger, opts...)
	return handler, func() {
	}, nil
}
