// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/transport/http"
	"github.com/l-vitaly/imgprocessing/pkg/service"
	http2 "net/http"
)

// Injectors from wire.go:

func SetupHTTPHandler(savedPath string, logger log.Logger, opts ...http.ServerOption) (http2.Handler, func(), error) {
	serviceInterface := ProvideService(savedPath, logger)
	set := service.MakeEndpoints(serviceInterface)
	encodeDecodeSet := service.MakeEncodeDecodeSet()
	handler := service.NewHTTPHandler(serviceInterface, set, encodeDecodeSet, logger, opts...)
	return handler, func() {
	}, nil
}

// wire.go:

func ProvideService(
	savePath string,
	logger log.Logger,
) service.Interface {
	return service.NewLoggingService(service.NewService(savePath), logger)
}
